"""empty message

Revision ID: 0003_remove_constr
Revises: 0002_fix_db_model
Create Date: 2025-11-24 15:46:00.178289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_remove_constr'
down_revision: Union[str, None] = '0002_fix_db_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_for_user', 'payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chat_for_user', 'payments', ['user_id', 'transaction_id'])
    # ### end Alembic commands ###
